name: Run Cadence Lint
on: push

jobs:
  run-cadence-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install Flow CLI
        run: |
          brew update
          brew install flow-cli
          flow init --reset

      - name: Run Cadence Lint
        run: |
          echo "Running Cadence linter on all .cdc files in the current repository"
          flow cadence lint **/*.cdc
