name: Run Cadence Lint
on: push

jobs:
  run-cadence-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Install Flow CLI
        run: |
          brew update
          brew install flow-cli

      - name: Initialize Flow
        run: |
          if [ ! -f flow.json ]; then
            echo "Initializing Flow project..."
            flow init
          else
            echo "Flow project already initialized."
          fi

      - name: Start Flow Emulator
        run: |
          echo "Starting Flow emulator in the background..."
          nohup flow emulator start > emulator.log 2>&1 &
          sleep 5 # Wait for the emulator to start

      - name: Run Transaction
        run: |
          echo "Running recipe transaction with Flow emulator..."
          flow transactions send cadence/transaction.cdc --signer emulator-account


      - name: Run Cadence Lint
        run: |
          echo "Running Cadence linter on all .cdc files in the current repository"
          flow cadence lint **/cadence/*.cdc
